### ISSUE TITLE
 cannot find -lcudart

### ISSUE THREAD

**Issue by ponytaill** [FurryMushroom/Quantization_work_of_DesignOrder#1]
您好，今天我在安装torch-int的时候遇到这个报错，您的文件中并没有说明lcudart是如何处理的，即使我将static全部删除也会显示找不到lcudart，你有任何建议吗？
/root/miniconda3/envs/smq/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcudart
/root/miniconda3/envs/smq/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcublas_static
/root/miniconda3/envs/smq/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcublasLt_static
/root/miniconda3/envs/smq/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lculibos
/root/miniconda3/envs/smq/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcudart
/root/miniconda3/envs/smq/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcudart_static

**Comment by FurryMushroom** [comment]
您好。你可以用我类似的方式搜索包含关键字lcudart的lib文件，或者尝试去掉l，变成cudart。

**Comment by ponytaill** [comment]
> 您好。你可以用我类似的方式搜索包含关键字lcudart的lib文件，或者尝试去掉l，变成cudart。

您好，感谢您的回复。就在刚才，我已经成功解决我的问题了，具体方法为创建软链接，sudo ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib/libcudart.so (代码仅用作示例)。在此之后，我按照您的方法去掉static后缀，可以安装成功了，并已通过测试。再次感谢您的工作。
