### ISSUE TITLE
Question about SmoothQuant

### ISSUE THREAD

**Issue by ponytaill** [FurryMushroom/Quantization_work_of_DesignOrder#2]
您好，请问您对SmoothQuant算法的代码有过深入了解吗？我最近正在修改SmoothQuant的代码使其在Phi-2模型上运行，但是遇到了不少迷惑的地方，想请教一下。

**Comment by FurryMushroom** [comment]
抱歉，这我没有。



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 23, 2024 18:28 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [FurryMushroom/Quantization_work_of_DesignOrder] Question aboutSmoothQuant (Issue #2)




 
您好，请问您对SmoothQuant算法的代码有过深入了解吗？我最近正在修改SmoothQuant的代码使其在Phi-2模型上运行，但是遇到了不少迷惑的地方，想请教一下。
